name: Link PR to Issue by Title

on:
  pull_request:
    types: [opened, edited]

jobs:
  link_pr_to_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract issue number from PR title
        id: extract
        run: |
          ISSUE_REF=$(echo "${{ github.event.pull_request.title }}" | grep -oE '#([0-9]+)' | head -n1 | tr -d '#')
          if [[ -n "$ISSUE_REF" ]]; then
            echo "issue_number=$ISSUE_REF" >> $GITHUB_OUTPUT
          else
            echo "No issue reference found in PR title"
            exit 0
          fi

      - name: Comment on issue with PR link
        run: |
          ISSUE_NUMBER=${{ steps.extract.outputs.issue_number }}
          PR_URL=${{ github.event.pull_request.html_url }}
          PR_TITLE=$(echo "${{ github.event.pull_request.title }}" | sed 's/"/\\"/g')

          gh issue comment "$ISSUE_NUMBER" --body "🔗 Открыт новый PR, связанный с этой задачей: [$(printf "%s" "$PR_TITLE")]($PR_URL)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}