name: Summarize new issues

on:
  issues:
    types: [opened]

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      models: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AI inference
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Прочитай эту задачу и подробно объясни, о чём она. Представь, что ты говоришь с начинающим разработчиком, который может не знать всех терминов.

            1. Кратко переформулируй суть задачи простыми словами.
            2. Объясни ключевые технические термины, которые встречаются в задаче.
            3. Определи, какие библиотеки или инструменты могут понадобиться для реализации этой задачи.
            4. Составь список тем или навыков, которые нужно изучить, чтобы решить эту задачу.
            5. (Если уместно) Приведи простой пример или аналогию, которая поможет понять задачу лучше.
            6. Мы пишем на Java, Spring Boot.
            Title: ${{ github.event.issue.title }}
            Body: ${{ github.event.issue.body }}

      - name: Comment with AI summary
        run: |
          gh issue comment $ISSUE_NUMBER --body '${{ steps.inference.outputs.response }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          RESPONSE: ${{ steps.inference.outputs.response }}
